import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile, mkdir, access } from "fs/promises";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * After each build, copy the plugin artifacts into the Obsidian vault's
 * plugin folder so a reload picks up the fresh build. The build output
 * dir (this repo) and the vault's plugin dir are separate locations;
 * without this sync Obsidian keeps loading a stale copy.
 *
 * Target is configurable via PERSPECTA_VAULT_PLUGIN_DIR; defaults to the
 * Perspecta-Dev vault. If the target doesn't exist (e.g. CI or another
 * machine) the copy is silently skipped so the build never fails.
 */
const VAULT_PLUGIN_DIR =
  process.env.PERSPECTA_VAULT_PLUGIN_DIR ||
  "/Users/wrede/Documents/Obsidian Vaults/Perspecta-Dev/.obsidian/plugins/perspecta-slides";

const ARTIFACTS = ["main.js", "manifest.json", "styles.css", "preload.js"];

async function syncToVault() {
  try {
    await mkdir(VAULT_PLUGIN_DIR, { recursive: true });
  } catch {
    // Parent path doesn't exist / not writable — skip sync.
    return;
  }
  for (const file of ARTIFACTS) {
    try {
      await access(file);
      await copyFile(file, join(VAULT_PLUGIN_DIR, file));
    } catch {
      // Artifact missing (e.g. styles.css optional) — skip just this one.
    }
  }
  console.log(`[esbuild] Synced ${ARTIFACTS.join(", ")} → ${VAULT_PLUGIN_DIR}`);
}

/** esbuild plugin: run the vault sync after every successful build. */
const vaultSyncPlugin = {
  name: "perspecta-vault-sync",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length === 0) {
        await syncToVault();
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts", "preload.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@electron/remote",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outbase: ".",
  outdir: ".",
  plugins: [vaultSyncPlugin],
  loader: {
    ".css": "text",  // Load CSS files as text strings
    ".wasm": "base64",  // Inline .wasm files as base64 strings (decoded at runtime)
    ".frag": "text",  // Inline GLSL fragment shaders as text strings
    ".woff2": "base64",  // Inline bundled built-in fonts (Inter) as base64 for @font-face data URLs
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
