/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


// preload.ts
var { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("nativeWindow", {
  /**
   * Signal to main process that a drag has been detected
   * Main process will start tracking mouse position
   */
  startDragging: () => {
    ipcRenderer.send("presentation-window-drag-start");
  },
  /**
   * Send cursor position delta to main process while dragging
   * Main process uses this to move the window
   */
  updateDragPosition: (dx, dy) => {
    ipcRenderer.send("presentation-window-drag-move", { dx, dy });
  },
  /**
   * Signal to main process that dragging has ended
   */
  stopDragging: () => {
    ipcRenderer.send("presentation-window-drag-stop");
  }
});
contextBridge.exposeInMainWorld("electron", {
  ipcRenderer: {
    send: (channel, args) => {
      ipcRenderer.send(channel, args);
    },
    on: (channel, func) => {
      ipcRenderer.on(channel, (event, ...args) => func(...args));
    }
  }
});
