/**
 * SlideMutationService — the write-side operations on a Perspecta deck
 * file: reorder, append, tidy, per-slide metadata, hidden state, and
 * deck frontmatter.
 *
 * Extracted from main.ts. Each method performs an atomic
 * `vault.process` transform (race-safe against concurrent edits) using
 * the pure split/parse/serialise helpers from SlideChunkSerializer.
 *
 * The service is deliberately free of view orchestration. It owns the
 * *content transform* and returns a small result describing what
 * happened; the plugin decides how to react (navigate to a slide, show
 * a Notice, refresh sidebars, invalidate the presentation cache). This
 * keeps the service dependency-light (just `app` + `parser`) and leaves
 * Obsidian-view coupling in the plugin where it belongs.
 */

import type { App, TFile } from 'obsidian';
import type { SlideParser } from '../parser/SlideParser';
import {
  splitBodyAtSeparators,
  joinSlideChunksWithSeparators,
  parseSlideChunk,
  serializeSlideChunk,
  tidySlideChunk,
} from './SlideChunkSerializer';

/** Split a document into its frontmatter block and body. */
function splitFrontmatter(content: string): { frontmatter: string; body: string } {
  const lines = content.split('\n');
  let inFrontmatter = false;
  let frontmatterEnd = 0;
  for (let i = 0; i < lines.length; i++) {
    if (i === 0 && lines[i].trim() === '---') {
      inFrontmatter = true;
      continue;
    }
    if (inFrontmatter && lines[i].trim() === '---') {
      frontmatterEnd = i + 1;
      break;
    }
  }
  return {
    frontmatter: lines.slice(0, frontmatterEnd).join('\n'),
    body: lines.slice(frontmatterEnd).join('\n'),
  };
}

/** Recombine a frontmatter block and body into a document. */
function joinFrontmatter(frontmatter: string, body: string): string {
  return frontmatter + (frontmatter ? '\n' : '') + body;
}

export type ReorderResult =
  | { status: 'reordered'; content: string; toIndex: number }
  | { status: 'out-of-range' }
  | { status: 'footnotes-slide' };

export interface AppendResult {
  /** New document content, or null if nothing was produced. */
  content: string | null;
}

export interface TidyResult {
  status: 'tidied' | 'already-tidy';
  content: string | null;
  count: number;
}

export interface MutationResult {
  /** New document content if the file changed, else null. */
  content: string | null;
}

export class SlideMutationService {
  constructor(
    private app: App,
    private parser: SlideParser
  ) {}

  /**
   * Move a slide from one position to another. Refuses to move the
   * auto-generated footnotes slide (it must stay last) and no-ops on
   * out-of-range / same-position requests.
   */
  async reorder(file: TFile, fromIndex: number, toIndex: number): Promise<ReorderResult> {
    let result: ReorderResult = { status: 'out-of-range' };

    await this.app.vault.process(file, (content) => {
      const presentation = this.parser.parse(content);

      if (
        fromIndex < 0 ||
        fromIndex >= presentation.slides.length ||
        toIndex < 0 ||
        toIndex >= presentation.slides.length ||
        fromIndex === toIndex
      ) {
        result = { status: 'out-of-range' };
        return content;
      }

      // Prevent reordering the auto-generated footnotes slide.
      const lastSlideIndex = presentation.slides.length - 1;
      const lastSlide = presentation.slides[lastSlideIndex];
      const isAutoGeneratedFootnotesSlide =
        lastSlide.elements.length === 0 && lastSlide.footnotes && lastSlide.footnotes.length > 0;
      if (
        isAutoGeneratedFootnotesSlide &&
        (fromIndex === lastSlideIndex || toIndex === lastSlideIndex)
      ) {
        result = { status: 'footnotes-slide' };
        return content;
      }

      const { frontmatter, body } = splitFrontmatter(content);
      const { slideRawContents, separators } = splitBodyAtSeparators(body);
      const [movedSlide] = slideRawContents.splice(fromIndex, 1);
      slideRawContents.splice(toIndex, 0, movedSlide);

      const newContent = joinFrontmatter(
        frontmatter,
        joinSlideChunksWithSeparators(slideRawContents, separators)
      );
      result = { status: 'reordered', content: newContent, toIndex };
      return newContent;
    });

    return result;
  }

  /**
   * Append a new blank slide. If the deck ends with a footnote-
   * definitions block, the slide is inserted before it (footnotes must
   * stay at the bottom) with generous padding so the user has room to
   * type; otherwise it's appended at the very end.
   */
  async appendSlide(file: TFile): Promise<AppendResult> {
    let producedContent: string | null = null;

    await this.app.vault.process(file, (content) => {
      const lines = content.split('\n');
      let firstFootnoteLineIndex = -1;
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].match(/^\[\^([^\]]+)\]:\s*(.*)$/)) {
          firstFootnoteLineIndex = i;
          break;
        }
      }

      if (firstFootnoteLineIndex >= 0) {
        // Insert new slide BEFORE the footnote definitions block.
        let emptyLinesBefore = 0;
        for (let i = firstFootnoteLineIndex - 1; i >= 0; i--) {
          if (lines[i].trim() === '') {
            emptyLinesBefore++;
          } else {
            break;
          }
        }
        const targetEmptyLines = Math.max(5, emptyLinesBefore);
        const contentEndIndex = firstFootnoteLineIndex - emptyLinesBefore;
        const beforeFootnotes = lines.slice(0, contentEndIndex).join('\n').trimEnd();
        const footnoteDefinitions = lines.slice(firstFootnoteLineIndex).join('\n');
        const emptyLinesPadding = '\n'.repeat(targetEmptyLines);
        producedContent =
          beforeFootnotes +
          '\n\nlayout: default\n\n# New Slide\n\nAdd your content here...' +
          emptyLinesPadding +
          '\n---\n\n' +
          footnoteDefinitions;
      } else {
        producedContent =
          content.trimEnd() +
          '\n\n---\n\nlayout: default\n\n# New Slide\n\nAdd your content here...\n';
      }
      return producedContent;
    });

    return { content: producedContent };
  }

  /**
   * Run `tidySlideChunk` on every slide. Frontmatter and separator lines
   * are preserved. Returns `already-tidy` (with null content) when the
   * transform is a no-op, so the caller can show the right message.
   */
  async tidyAll(file: TFile): Promise<TidyResult> {
    let count = 0;
    let alreadyTidy = false;
    let producedContent: string | null = null;

    await this.app.vault.process(file, (content) => {
      const { frontmatter, body } = splitFrontmatter(content);
      const { slideRawContents, separators } = splitBodyAtSeparators(body);
      const tidied = slideRawContents.map((chunk) => tidySlideChunk(chunk));
      count = tidied.length;

      const newContent = joinFrontmatter(
        frontmatter,
        joinSlideChunksWithSeparators(tidied, separators)
      );
      if (newContent === content) {
        alreadyTidy = true;
        return content;
      }
      producedContent = newContent;
      return newContent;
    });

    return {
      status: alreadyTidy ? 'already-tidy' : 'tidied',
      content: producedContent,
      count,
    };
  }

  /**
   * Set per-slide metadata keys (layout, mode, background, opacity,
   * hide-overlay, chapter, …). Values of `undefined`/`null`/`''` delete
   * the key. `backgroundOpacity` (0–1) is written as a percentage on the
   * `opacity` key; `hideOverlay` is written as `hide-overlay`.
   */
  async updateMetadata(
    file: TFile,
    slideIndex: number,
    metadata: Record<string, unknown>
  ): Promise<MutationResult> {
    let producedContent: string | null = null;

    await this.app.vault.process(file, (content) => {
      const { frontmatter, body } = splitFrontmatter(content);
      const { slideRawContents, separators } = splitBodyAtSeparators(body);

      if (slideIndex < 0 || slideIndex >= slideRawContents.length) {
        return content;
      }

      const { meta, content: slideContent } = parseSlideChunk(slideRawContents[slideIndex]);

      for (const [key, value] of Object.entries(metadata)) {
        const writeKey = key === 'hideOverlay' ? 'hide-overlay' : key;
        if (value === undefined || value === null || value === '') {
          delete meta[writeKey];
          delete meta[key]; // remove any alias variant too
          continue;
        }
        if (typeof value === 'boolean') {
          meta[writeKey] = value ? 'true' : 'false';
        } else if (typeof value === 'number') {
          if (key === 'backgroundOpacity') {
            meta['opacity'] = `${Math.round(value * 100)}%`;
          } else {
            meta[writeKey] = String(value);
          }
        } else {
          meta[writeKey] = String(value);
        }
      }

      slideRawContents[slideIndex] = serializeSlideChunk(meta, slideContent);
      const newContent = joinFrontmatter(
        frontmatter,
        joinSlideChunksWithSeparators(slideRawContents, separators)
      );
      producedContent = newContent;
      return newContent;
    });

    return { content: producedContent };
  }

  /**
   * Toggle a slide's hidden state by adding/removing the `(hidden)`
   * suffix on its `layout` meta value. Idempotent in both directions.
   */
  async setHidden(file: TFile, slideIndex: number, hidden: boolean): Promise<MutationResult> {
    let producedContent: string | null = null;

    await this.app.vault.process(file, (content) => {
      const { frontmatter, body } = splitFrontmatter(content);
      const { slideRawContents, separators } = splitBodyAtSeparators(body);

      if (slideIndex < 0 || slideIndex >= slideRawContents.length) {
        return content;
      }

      const { meta, content: slideContent } = parseSlideChunk(slideRawContents[slideIndex]);

      if (hidden) {
        const currentLayout = (meta.layout ?? '').trim();
        if (currentLayout === '') {
          meta.layout = '(hidden)';
        } else if (!currentLayout.includes('(hidden)')) {
          meta.layout = `${currentLayout} (hidden)`;
        }
        // else: already hidden, nothing to do
      } else {
        if (meta.layout !== undefined) {
          const cleaned = meta.layout.replace(/\s*\(hidden\)\s*/, '').trim();
          if (cleaned === '') {
            delete meta.layout;
          } else {
            meta.layout = cleaned;
          }
        }
      }

      slideRawContents[slideIndex] = serializeSlideChunk(meta, slideContent);
      const newContent = joinFrontmatter(
        frontmatter,
        joinSlideChunksWithSeparators(slideRawContents, separators)
      );
      producedContent = newContent;
      return newContent;
    });

    return { content: producedContent };
  }

  /**
   * Merge updates into the deck's YAML frontmatter. Keys are converted
   * from camelCase to kebab-case; arrays serialise as comma-separated
   * values; empty values delete the key. Values containing `:`/`#`/
   * leading space are quoted.
   */
  async updateFrontmatter(
    file: TFile,
    updates: Record<string, unknown>
  ): Promise<MutationResult> {
    let producedContent: string | null = null;

    await this.app.vault.process(file, (content) => {
      const lines = content.split('\n');

      let hasFrontmatter = false;
      let frontmatterStart = -1;
      let frontmatterEnd = -1;
      for (let i = 0; i < lines.length; i++) {
        if (i === 0 && lines[i].trim() === '---') {
          hasFrontmatter = true;
          frontmatterStart = 0;
          continue;
        }
        if (hasFrontmatter && frontmatterStart >= 0 && lines[i].trim() === '---') {
          frontmatterEnd = i;
          break;
        }
      }

      const existingFM: Record<string, string> = {};
      if (hasFrontmatter && frontmatterEnd > frontmatterStart) {
        for (let i = frontmatterStart + 1; i < frontmatterEnd; i++) {
          const line = lines[i];
          const colonIndex = line.indexOf(':');
          if (colonIndex > 0) {
            const key = line.slice(0, colonIndex).trim();
            let value = line.slice(colonIndex + 1).trim();
            if (
              (value.startsWith('"') && value.endsWith('"')) ||
              (value.startsWith("'") && value.endsWith("'"))
            ) {
              value = value.slice(1, -1);
            }
            existingFM[key] = value;
          }
        }
      }

      for (const [key, value] of Object.entries(updates)) {
        const yamlKey = key
          .replace(/([A-Z])/g, '-$1')
          .toLowerCase()
          .replace(/^-/, '');

        if (value === undefined || value === null || value === '') {
          delete existingFM[yamlKey];
          delete existingFM[key];
        } else if (typeof value === 'boolean') {
          existingFM[yamlKey] = value ? 'true' : 'false';
        } else if (Array.isArray(value)) {
          existingFM[yamlKey] = value.join(', ');
        } else {
          existingFM[yamlKey] = String(value);
        }
      }

      const fmLines = ['---'];
      for (const [key, value] of Object.entries(existingFM)) {
        if (value.includes(':') || value.includes('#') || value.startsWith(' ')) {
          fmLines.push(`${key}: "${value}"`);
        } else {
          fmLines.push(`${key}: ${value}`);
        }
      }
      fmLines.push('---');

      const bodyStart = hasFrontmatter ? frontmatterEnd + 1 : 0;
      const bodyLines = lines.slice(bodyStart);
      const newContent = fmLines.join('\n') + '\n' + bodyLines.join('\n');
      producedContent = newContent;
      return newContent;
    });

    return { content: producedContent };
  }
}
